const $ = selector => document.querySelector(selector);
const message = (text, success = false) => { const element = $('#message'); element.textContent = text; element.className = `message${success ? ' success' : ''}`; };
const password = () => $('#write-password').value;
async function request(path, options = {}) { const response = await fetch(path, { ...options, headers: { accept: 'application/json', ...(options.body ? { 'content-type': 'application/json' } : {}), ...(password() ? { 'x-event-write-password': password() } : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `Request failed with HTTP ${response.status}.`); return data; }
function setText(selector, value) { $(selector).textContent = value ?? '—'; }
async function refreshStatus() { try { const [status, health, snapshot] = await Promise.all([request('/api/v1/status'), request('/api/v1/health'), fetch('/api/v1/snapshot').then(response => response.ok ? response.json() : null)]); setText('#status-connection', status.connection); setText('#status-quality', status.quality); setText('#status-source', status.source || '—'); setText('#status-event', status.event || 'No active event'); setText('#status-epoch', health.hubEpoch); setText('#status-snapshot', snapshot?.snapshotId || 'No snapshot'); if (snapshot) { $('#event-session-id').value = snapshot.eventSessionId; $('#event-name').value = snapshot.event.name; $('#event-source-url').value = snapshot.event.sourceUrl || ''; } } catch (error) { message(error.message); } }
function renderHistory(items) { const list = $('#announcement-list'); list.replaceChildren(); if (!items.length) { const empty = document.createElement('li'); empty.className = 'muted'; empty.textContent = 'No announcements.'; list.append(empty); return; } for (const item of items) { const row = document.createElement('li'); row.className = `announcement ${item.status}`; const title = document.createElement('strong'); title.textContent = `${item.title} · ${item.importance}/3`; const body = document.createElement('span'); body.className = 'body'; body.textContent = item.body; const meta = document.createElement('small'); meta.textContent = `${item.status} · ${item.createdAt} · ${item.createdByDeviceId}`; row.append(title, body, meta); if (item.status === 'active') { const actions = document.createElement('div'); actions.className = 'announcement-actions'; const clear = document.createElement('button'); clear.className = 'danger'; clear.type = 'button'; clear.textContent = 'Clear globally'; clear.addEventListener('click', async () => { try { await request(`/api/v1/announcements/${encodeURIComponent(item.announcementId)}/clear`, { method: 'POST' }); message('Announcement cleared for all consumers.', true); await refreshHistory(); } catch (error) { message(error.message); } }); actions.append(clear); row.append(actions); } list.append(row); } }
async function refreshHistory() { try { const data = await request('/api/v1/announcements/history'); renderHistory(data.items); } catch (error) { renderHistory([]); message(error.message); } }
$('#refresh-status').addEventListener('click', refreshStatus);
$('#refresh-history').addEventListener('click', refreshHistory);
$('#event-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/v1/admin/event', { method: 'POST', body: JSON.stringify({ eventSessionId: $('#event-session-id').value.trim(), event: { id: $('#event-session-id').value.trim(), name: $('#event-name').value.trim() || 'Selected event', sourceUrl: $('#event-source-url').value.trim() || undefined } }) }); message('Event selected. Waiting for a trusted source snapshot.', true); await refreshStatus(); await refreshHistory(); } catch (error) { message(error.message); } });
$('#deactivate').addEventListener('click', async () => { if (!window.confirm('Deactivate the selected event for this hub?')) return; try { await request('/api/v1/admin/event/deactivate', { method: 'POST', body: '{}' }); message('Event deactivated. No event is being served.', true); await refreshStatus(); await refreshHistory(); } catch (error) { message(error.message); } });
$('#announcement-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/v1/announcements', { method: 'POST', body: JSON.stringify({ title: $('#announcement-title').value.trim(), body: $('#announcement-body').value.trim(), importance: Number($('#announcement-importance').value), createdByDeviceId: $('#announcement-device').value.trim() }) }); message('Announcement published to all consumers.', true); $('#announcement-form').reset(); $('#announcement-importance').value = '3'; $('#announcement-device').value = 'hub-admin'; await refreshHistory(); } catch (error) { message(error.message); } });
$('#clear-form').addEventListener('click', () => $('#announcement-form').reset());
void refreshStatus(); void refreshHistory();
