const $ = selector => document.querySelector(selector);
const message = (text, success = false) => { const element = $('#message'); element.textContent = text; element.className = `message${success ? ' success' : ''}`; };
async function request(path, options = {}) { const response = await fetch(path, { ...options, headers: { accept: 'application/json', ...(options.body ? { 'content-type': 'application/json' } : {}), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || `Request failed with HTTP ${response.status}.`); return data; }
function setText(selector, value) { $(selector).textContent = value ?? '—'; }
function setMetadataEditable(editable) { for (const id of ['event-session-id', 'event-name']) $('#' + id).readOnly = !editable; $('#apply-metadata').disabled = !editable; }
async function refreshStatus() { try { const [status, health, snapshot] = await Promise.all([request('/api/v1/status'), request('/api/v1/health'), fetch('/api/v1/snapshot').then(response => response.ok ? response.json() : null)]); setText('#status-connection', status.connection); setText('#status-quality', status.quality); setText('#status-race-status', status.raceStatus || 'No active race'); setText('#status-source', status.source || '—'); setText('#status-event', status.event || 'No active event'); setText('#status-epoch', health.hubEpoch); setText('#status-snapshot', snapshot?.snapshotId || 'No snapshot'); if (snapshot) { $('#event-session-id').value = snapshot.eventSessionId; $('#event-name').value = snapshot.event.name; $('#event-source-url').value = snapshot.event.sourceUrl || ''; } } catch (error) { message(error.message); } }
function renderHistory(items) { const list = $('#announcement-list'); list.replaceChildren(); if (!items.length) { const empty = document.createElement('li'); empty.className = 'muted'; empty.textContent = 'No announcements.'; list.append(empty); return; } for (const item of items) { const row = document.createElement('li'); row.className = `announcement ${item.status}`; const title = document.createElement('strong'); title.textContent = `${item.title} · ${item.importance}/3`; const body = document.createElement('span'); body.className = 'body'; body.textContent = item.body; const meta = document.createElement('small'); meta.textContent = `${item.status} · ${item.createdAt} · ${item.createdByDeviceId}`; row.append(title, body, meta); if (item.status === 'active') { const actions = document.createElement('div'); actions.className = 'announcement-actions'; const clear = document.createElement('button'); clear.className = 'danger'; clear.type = 'button'; clear.textContent = 'Clear globally'; clear.addEventListener('click', async () => { try { await request(`/api/v1/announcements/${encodeURIComponent(item.announcementId)}/clear`, { method: 'POST' }); message('Announcement cleared for all consumers.', true); await refreshHistory(); } catch (error) { message(error.message); } }); actions.append(clear); row.append(actions); } list.append(row); } }
async function refreshHistory() { try { const data = await request('/api/v1/announcements/history'); renderHistory(data.items); } catch (error) { renderHistory([]); message(error.message); } }
$('#refresh-status').addEventListener('click', refreshStatus);
$('#refresh-history').addEventListener('click', refreshHistory);
$('#source-form').addEventListener('submit', async event => { event.preventDefault(); const sourceUrl = $('#event-source-url').value.trim(); if (!sourceUrl) return; setText('#source-message', 'Connecting to LiveFPV and loading the event…'); try { const result = await request('/api/v1/admin/source', { method: 'POST', body: JSON.stringify({ sourceUrl }) }); const name = result.snapshot?.event?.name || result.status?.event || 'event'; message(`Connected. Event loaded: ${name}.`, true); setText('#source-message', `LiveFPV link accepted · ${name}`); setMetadataEditable(false); await refreshStatus(); await refreshHistory(); } catch (error) { message(error.message); setText('#source-message', 'Connection failed. The previous trusted state was not replaced.'); } });
$('#manual-metadata').addEventListener('change', event => setMetadataEditable(event.target.checked));
$('#apply-metadata').addEventListener('click', async () => { try { await request('/api/v1/admin/metadata', { method: 'POST', body: JSON.stringify({ eventSessionId: $('#event-session-id').value.trim(), event: { name: $('#event-name').value.trim() || 'Selected event', sourceUrl: $('#event-source-url').value.trim() || undefined } }) }); message('Metadata override applied.', true); setText('#source-message', 'Manual metadata override applied.'); setMetadataEditable(false); $('#manual-metadata').checked = false; await refreshStatus(); } catch (error) { message(error.message); setText('#source-message', `Metadata override failed: ${error.message}`); } });
$('#disconnect-source').addEventListener('click', async () => { if (!window.confirm('Disconnect the LiveFPV source and clear the active event?')) return; try { await request('/api/v1/admin/event/deactivate', { method: 'POST', body: '{}' }); message('Source disconnected. No event is being served.', true); setText('#source-message', 'Source disconnected.'); $('#manual-metadata').checked = false; setMetadataEditable(false); await refreshStatus(); await refreshHistory(); } catch (error) { message(error.message); } });
$('#announcement-form').addEventListener('submit', async event => { event.preventDefault(); try { await request('/api/v1/announcements', { method: 'POST', body: JSON.stringify({ title: $('#announcement-title').value.trim(), body: $('#announcement-body').value.trim(), importance: Number($('#announcement-importance').value), createdByDeviceId: $('#announcement-device').value.trim() }) }); message('Announcement published to all consumers.', true); $('#announcement-form').reset(); $('#announcement-importance').value = '3'; $('#announcement-device').value = 'hub-admin'; await refreshHistory(); } catch (error) { message(error.message); } });
$('#clear-form').addEventListener('click', () => $('#announcement-form').reset());
void refreshStatus(); void refreshHistory();
